# Test to see if the Docker build process works

# Creates a GitHub release
on:
  push:
    branches-ignore:
      - main
    tags-ignore: # Ensure that we're not running this on our release tags - This will be an actual build.
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Docker

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        if: github.actor != 'dependabot[bot]'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            app_version=${{ github.ref_name }}-${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Dependabot - Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        if: github.actor == 'dependabot[bot]'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            app_version=dependabot-${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:dependabot
